In [1]:
a=4
print(a)

4

In [2]:
pip install pandas

^C
Note: you may need to restart the kernel to use updated packages.

In [3]:
! pip install pandas

Collecting pandas
  Downloading pandas-2.2.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.2.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jsr\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\jsr\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.2.3-cp312-cp312-win_amd64.whl (11.5 MB)
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
    --------------------------------------- 0.3/11.5 MB ? eta -:--:--
    --------------------------------------- 0.3/11.5 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.5 MB 453.5 kB/s eta 0:00:25
   - -------------------------------------- 0.5/11.5 MB 453.5 kB/s eta 0:00:25
   -- ------------------------------------- 0.8/11.5 MB 644.9 kB/s eta 0:00:17
   --- ------------------------------------ 1.0/11.5 MB 718.9 kB/s eta 0:00:15
   ---- ----------------------------------- 1.3/11.5 MB 817.9 kB/s eta 0:00:13
   ----- ---------------------------------- 1.6/11.5 MB 911.5 kB/s eta 0:00:11
   ----- ---------------------------------- 1.6/11.5 MB 911.5 kB/s eta 0:00:11
   ----- ---------------------------------- 1.6/11.5 MB 911.5 kB/s eta 0:00:11
   ------ --------------------------------- 1.8/11.5 MB 740.2 kB/s eta 0:00:14
   ------- -------------------------------- 2.1/11.5 MB 738.4 kB/s eta 0:00:13
   -------- ------------------------------- 2.4/11.5 MB 771.3 kB/s eta 0:00:12
   -------- ------------------------------- 2.4/11.5 MB 771.3 kB/s eta 0:00:12
   --------- ------------------------------ 2.6/11.5 MB 747.3 kB/s eta 0:00:12
   --------- ------------------------------ 2.6/11.5 MB 747.3 kB/s eta 0:00:12
   ---------- ----------------------------- 2.9/11.5 MB 742.2 kB/s eta 0:00:12
   ---------- ----------------------------- 2.9/11.5 MB 742.2 kB/s eta 0:00:12
   ---------- ----------------------------- 3.1/11.5 MB 729.5 kB/s eta 0:00:12
   ---------- ----------------------------- 3.1/11.5 MB 729.5 kB/s eta 0:00:12
   ---------- ----------------------------- 3.1/11.5 MB 729.5 kB/s eta 0:00:12
   ----------- ---------------------------- 3.4/11.5 MB 699.0 kB/s eta 0:00:12
   ----------- ---------------------------- 3.4/11.5 MB 699.0 kB/s eta 0:00:12
   ----------- ---------------------------- 3.4/11.5 MB 699.0 kB/s eta 0:00:12
   ----------- ---------------------------- 3.4/11.5 MB 699.0 kB/s eta 0:00:12
   ----------- ---------------------------- 3.4/11.5 MB 699.0 kB/s eta 0:00:12
   ------------ --------------------------- 3.7/11.5 MB 616.0 kB/s eta 0:00:13
   ------------- -------------------------- 3.9/11.5 MB 616.5 kB/s eta 0:00:13
   ------------- -------------------------- 3.9/11.5 MB 616.5 kB/s eta 0:00:13
   -------------- ------------------------- 4.2/11.5 MB 624.4 kB/s eta 0:00:12
   --------------- ------------------------ 4.5/11.5 MB 637.6 kB/s eta 0:00:12
   --------------- ------------------------ 4.5/11.5 MB 637.6 kB/s eta 0:00:12
   ---------------- ----------------------- 4.7/11.5 MB 636.6 kB/s eta 0:00:11
   ---------------- ----------------------- 4.7/11.5 MB 636.6 kB/s eta 0:00:11
   ---------------- ----------------------- 4.7/11.5 MB 636.6 kB/s eta 0:00:11
   ---------------- ----------------------- 4.7/11.5 MB 636.6 kB/s eta 0:00:11
   ---------------- ----------------------- 4.7/11.5 MB 636.6 kB/s eta 0:00:11
   ---------------- ----------------------- 4.7/11.5 MB 636.6 kB/s eta 0:00:11
   ---------------- ----------------------- 4.7/11.5 MB 636.6 kB/s eta 0:00:11
   ---------------- ----------------------- 4.7/11.5 MB 636.6 kB/s eta 0:00:11
   ---------------- ----------------------- 4.7/11.5 MB 636.6 kB/s eta 0:00:11
   ---------------- ----------------------- 4.7/11.5 MB 636.6 kB/s eta 0:00:11
   ---------------- ----------------------- 4.7/11.5 MB 636.6 kB/s eta 0:00:11
   ---------------- ----------------------- 4.7/11.5 MB 636.6 kB/s eta 0:00:11
   ---------------- ----------------------- 4.7/11.5 MB 636.6 kB/s eta 0:00:11
   ---------------- ----------------------- 4.7/11.5 MB 636.6 kB/s eta 0:00:11
   ---------------- ----------------------- 4.7/11.5 MB 636.6 kB/s eta 0:00:11
   ---------------- ----------------------- 4.7/11.5 MB 636.6 kB/s eta 0:00:11
   ---------------- ----------------------- 4.7/11.5 MB 636.6 kB/s eta 0:00:11
   ----------------- ---------------------- 5.0/11.5 MB 449.4 kB/s eta 0:00:15
   ----------------- ---------------------- 5.0/11.5 MB 449.4 kB/s eta 0:00:15
   ----------------- ---------------------- 5.0/11.5 MB 449.4 kB/s eta 0:00:15
   ----------------- ---------------------- 5.0/11.5 MB 449.4 kB/s eta 0:00:15
   ----------------- ---------------------- 5.0/11.5 MB 449.4 kB/s eta 0:00:15
   ----------------- ---------------------- 5.0/11.5 MB 449.4 kB/s eta 0:00:15
   ----------------- ---------------------- 5.0/11.5 MB 449.4 kB/s eta 0:00:15
   ----------------- ---------------------- 5.0/11.5 MB 449.4 kB/s eta 0:00:15
   ----------------- ---------------------- 5.0/11.5 MB 449.4 kB/s eta 0:00:15
   ----------------- ---------------------- 5.0/11.5 MB 449.4 kB/s eta 0:00:15
   ----------------- ---------------------- 5.0/11.5 MB 449.4 kB/s eta 0:00:15
   ----------------- ---------------------- 5.0/11.5 MB 449.4 kB/s eta 0:00:15
   ----------------- ---------------------- 5.0/11.5 MB 449.4 kB/s eta 0:00:15
   ----------------- ---------------------- 5.0/11.5 MB 449.4 kB/s eta 0:00:15
   ----------------- ---------------------- 5.0/11.5 MB 449.4 kB/s eta 0:00:15
   ----------------- ---------------------- 5.0/11.5 MB 449.4 kB/s eta 0:00:15
   ----------------- ---------------------- 5.0/11.5 MB 449.4 kB/s eta 0:00:15
   ----------------- ---------------------- 5.0/11.5 MB 449.4 kB/s eta 0:00:15
   ----------------- ---------------------- 5.0/11.5 MB 449.4 kB/s eta 0:00:15
   ----------------- ---------------------- 5.0/11.5 MB 449.4 kB/s eta 0:00:15
   ----------------- ---------------------- 5.0/11.5 MB 449.4 kB/s eta 0:00:15
   ----------------- ---------------------- 5.0/11.5 MB 449.4 kB/s eta 0:00:15
   ------------------ --------------------- 5.2/11.5 MB 328.3 kB/s eta 0:00:20
   ------------------ --------------------- 5.2/11.5 MB 328.3 kB/s eta 0:00:20
   ------------------ --------------------- 5.2/11.5 MB 328.3 kB/s eta 0:00:20
   ------------------- -------------------- 5.5/11.5 MB 329.6 kB/s eta 0:00:19
   ------------------- -------------------- 5.5/11.5 MB 329.6 kB/s eta 0:00:19
   ------------------- -------------------- 5.5/11.5 MB 329.6 kB/s eta 0:00:19
   ------------------- -------------------- 5.5/11.5 MB 329.6 kB/s eta 0:00:19
   ------------------- -------------------- 5.5/11.5 MB 329.6 kB/s eta 0:00:19
   ------------------- -------------------- 5.5/11.5 MB 329.6 kB/s eta 0:00:19
   ------------------- -------------------- 5.5/11.5 MB 329.6 kB/s eta 0:00:19
   -------------------- ------------------- 5.8/11.5 MB 316.5 kB/s eta 0:00:19
   -------------------- ------------------- 5.8/11.5 MB 316.5 kB/s eta 0:00:19
   -------------------- ------------------- 5.8/11.5 MB 316.5 kB/s eta 0:00:19
   -------------------- ------------------- 5.8/11.5 MB 316.5 kB/s eta 0:00:19
   -------------------- ------------------- 5.8/11.5 MB 316.5 kB/s eta 0:00:19
   -------------------- ------------------- 5.8/11.5 MB 316.5 kB/s eta 0:00:19
   -------------------- ------------------- 6.0/11.5 MB 309.1 kB/s eta 0:00:18
   -------------------- ------------------- 6.0/11.5 MB 309.1 kB/s eta 0:00:18
   -------------------- ------------------- 6.0/11.5 MB 309.1 kB/s eta 0:00:18
   -------------------- ------------------- 6.0/11.5 MB 309.1 kB/s eta 0:00:18
   -------------------- ------------------- 6.0/11.5 MB 309.1 kB/s eta 0:00:18
   -------------------- ------------------- 6.0/11.5 MB 309.1 kB/s eta 0:00:18
   -------------------- ------------------- 6.0/11.5 MB 309.1 kB/s eta 0:00:18
   -------------------- ------------------- 6.0/11.5 MB 309.1 kB/s eta 0:00:18
   -------------------- ------------------- 6.0/11.5 MB 309.1 kB/s eta 0:00:18
   -------------------- ------------------- 6.0/11.5 MB 309.1 kB/s eta 0:00:18
   -------------------- ------------------- 6.0/11.5 MB 309.1 kB/s eta 0:00:18
   -------------------- ------------------- 6.0/11.5 MB 309.1 kB/s eta 0:00:18
   -------------------- ------------------- 6.0/11.5 MB 309.1 kB/s eta 0:00:18
   --------------------- ------------------ 6.3/11.5 MB 282.1 kB/s eta 0:00:19
   --------------------- ------------------ 6.3/11.5 MB 282.1 kB/s eta 0:00:19
   --------------------- ------------------ 6.3/11.5 MB 282.1 kB/s eta 0:00:19
   --------------------- ------------------ 6.3/11.5 MB 282.1 kB/s eta 0:00:19
   --------------------- ------------------ 6.3/11.5 MB 282.1 kB/s eta 0:00:19
   --------------------- ------------------ 6.3/11.5 MB 282.1 kB/s eta 0:00:19
   --------------------- ------------------ 6.3/11.5 MB 282.1 kB/s eta 0:00:19
   --------------------- ------------------ 6.3/11.5 MB 282.1 kB/s eta 0:00:19
   --------------------- ------------------ 6.3/11.5 MB 282.1 kB/s eta 0:00:19
   --------------------- ------------------ 6.3/11.5 MB 282.1 kB/s eta 0:00:19
   --------------------- ------------------ 6.3/11.5 MB 282.1 kB/s eta 0:00:19
   --------------------- ------------------ 6.3/11.5 MB 282.1 kB/s eta 0:00:19
   --------------------- ------------------ 6.3/11.5 MB 282.1 kB/s eta 0:00:19
   --------------------- ------------------ 6.3/11.5 MB 282.1 kB/s eta 0:00:19
   --------------------- ------------------ 6.3/11.5 MB 282.1 kB/s eta 0:00:19
   --------------------- ------------------ 6.3/11.5 MB 282.1 kB/s eta 0:00:19
   --------------------- ------------------ 6.3/11.5 MB 282.1 kB/s eta 0:00:19
   --------------------- ------------------ 6.3/11.5 MB 282.1 kB/s eta 0:00:19
   --------------------- ------------------ 6.3/11.5 MB 282.1 kB/s eta 0:00:19
   --------------------- ------------------ 6.3/11.5 MB 282.1 kB/s eta 0:00:19
   ---------------------- ----------------- 6.6/11.5 MB 244.2 kB/s eta 0:00:21
   ---------------------- ----------------- 6.6/11.5 MB 244.2 kB/s eta 0:00:21
   ---------------------- ----------------- 6.6/11.5 MB 244.2 kB/s eta 0:00:21
   ---------------------- ----------------- 6.6/11.5 MB 244.2 kB/s eta 0:00:21
   ---------------------- ----------------- 6.6/11.5 MB 244.2 kB/s eta 0:00:21
   ---------------------- ----------------- 6.6/11.5 MB 244.2 kB/s eta 0:00:21
   ---------------------- ----------------- 6.6/11.5 MB 244.2 kB/s eta 0:00:21
   ---------------------- ----------------- 6.6/11.5 MB 244.2 kB/s eta 0:00:21
   ----------------------- ---------------- 6.8/11.5 MB 238.2 kB/s eta 0:00:20
   ----------------------- ---------------- 6.8/11.5 MB 238.2 kB/s eta 0:00:20
   ----------------------- ---------------- 6.8/11.5 MB 238.2 kB/s eta 0:00:20
   ----------------------- ---------------- 6.8/11.5 MB 238.2 kB/s eta 0:00:20
   ----------------------- ---------------- 6.8/11.5 MB 238.2 kB/s eta 0:00:20
   ----------------------- ---------------- 6.8/11.5 MB 238.2 kB/s eta 0:00:20
   ----------------------- ---------------- 6.8/11.5 MB 238.2 kB/s eta 0:00:20
   ----------------------- ---------------- 6.8/11.5 MB 238.2 kB/s eta 0:00:20
   ----------------------- ---------------- 6.8/11.5 MB 238.2 kB/s eta 0:00:20
   ------------------------ --------------- 7.1/11.5 MB 231.3 kB/s eta 0:00:20
   ------------------------ --------------- 7.1/11.5 MB 231.3 kB/s eta 0:00:20
   ------------------------ --------------- 7.1/11.5 MB 231.3 kB/s eta 0:00:20
   ------------------------ --------------- 7.1/11.5 MB 231.3 kB/s eta 0:00:20
   ------------------------ --------------- 7.1/11.5 MB 231.3 kB/s eta 0:00:20
   ------------------------ --------------- 7.1/11.5 MB 231.3 kB/s eta 0:00:20
   ------------------------ --------------- 7.1/11.5 MB 231.3 kB/s eta 0:00:20
   ------------------------ --------------- 7.1/11.5 MB 231.3 kB/s eta 0:00:20
   ------------------------ --------------- 7.1/11.5 MB 231.3 kB/s eta 0:00:20
   ------------------------ --------------- 7.1/11.5 MB 231.3 kB/s eta 0:00:20
   ------------------------ --------------- 7.1/11.5 MB 231.3 kB/s eta 0:00:20
   ------------------------ --------------- 7.1/11.5 MB 231.3 kB/s eta 0:00:20
   ------------------------ --------------- 7.1/11.5 MB 231.3 kB/s eta 0:00:20
   ------------------------ --------------- 7.1/11.5 MB 231.3 kB/s eta 0:00:20
   ------------------------ --------------- 7.1/11.5 MB 231.3 kB/s eta 0:00:20
   ------------------------ --------------- 7.1/11.5 MB 231.3 kB/s eta 0:00:20
   ------------------------ --------------- 7.1/11.5 MB 231.3 kB/s eta 0:00:20
   ------------------------ --------------- 7.1/11.5 MB 231.3 kB/s eta 0:00:20
   ------------------------ --------------- 7.1/11.5 MB 231.3 kB/s eta 0:00:20
   ------------------------ --------------- 7.1/11.5 MB 231.3 kB/s eta 0:00:20
   ------------------------ --------------- 7.1/11.5 MB 231.3 kB/s eta 0:00:20
   ------------------------ --------------- 7.1/11.5 MB 231.3 kB/s eta 0:00:20
   ------------------------- -------------- 7.3/11.5 MB 132.7 kB/s eta 0:00:32
   ------------------------- -------------- 7.3/11.5 MB 132.7 kB/s eta 0:00:32
   ------------------------- -------------- 7.3/11.5 MB 132.7 kB/s eta 0:00:32
   ------------------------- -------------- 7.3/11.5 MB 132.7 kB/s eta 0:00:32
   ------------------------- -------------- 7.3/11.5 MB 132.7 kB/s eta 0:00:32
   ------------------------- -------------- 7.3/11.5 MB 132.7 kB/s eta 0:00:32
   ------------------------- -------------- 7.3/11.5 MB 132.7 kB/s eta 0:00:32
   ------------------------- -------------- 7.3/11.5 MB 132.7 kB/s eta 0:00:32
   ------------------------- -------------- 7.3/11.5 MB 132.7 kB/s eta 0:00:32
   ------------------------- -------------- 7.3/11.5 MB 132.7 kB/s eta 0:00:32
   ------------------------- -------------- 7.3/11.5 MB 132.7 kB/s eta 0:00:32
   ------------------------- -------------- 7.3/11.5 MB 132.7 kB/s eta 0:00:32
   ------------------------- -------------- 7.3/11.5 MB 132.7 kB/s eta 0:00:32
   ------------------------- -------------- 7.3/11.5 MB 132.7 kB/s eta 0:00:32
   ------------------------- -------------- 7.3/11.5 MB 132.7 kB/s eta 0:00:32
   ------------------------- -------------- 7.3/11.5 MB 132.7 kB/s eta 0:00:32
   ------------------------- -------------- 7.3/11.5 MB 132.7 kB/s eta 0:00:32
   ------------------------- -------------- 7.3/11.5 MB 132.7 kB/s eta 0:00:32
   ------------------------- -------------- 7.3/11.5 MB 132.7 kB/s eta 0:00:32
   ------------------------- -------------- 7.3/11.5 MB 132.7 kB/s eta 0:00:32
   ------------------------- -------------- 7.3/11.5 MB 132.7 kB/s eta 0:00:32
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   -------------------------- ------------- 7.6/11.5 MB 93.4 kB/s eta 0:00:42
   --------------------------- ------------ 7.9/11.5 MB 72.5 kB/s eta 0:00:51
   --------------------------- ------------ 7.9/11.5 MB 72.5 kB/s eta 0:00:51
   --------------------------- ------------ 7.9/11.5 MB 72.5 kB/s eta 0:00:51
   --------------------------- ------------ 7.9/11.5 MB 72.5 kB/s eta 0:00:51
   --------------------------- ------------ 7.9/11.5 MB 72.5 kB/s eta 0:00:51
   --------------------------- ------------ 7.9/11.5 MB 72.5 kB/s eta 0:00:51
   --------------------------- ------------ 7.9/11.5 MB 72.5 kB/s eta 0:00:51
   --------------------------- ------------ 7.9/11.5 MB 72.5 kB/s eta 0:00:51
   --------------------------- ------------ 7.9/11.5 MB 72.5 kB/s eta 0:00:51
   --------------------------- ------------ 7.9/11.5 MB 72.5 kB/s eta 0:00:51
   --------------------------- ------------ 7.9/11.5 MB 72.5 kB/s eta 0:00:51
   --------------------------- ------------ 7.9/11.5 MB 72.5 kB/s eta 0:00:51
   --------------------------- ------------ 7.9/11.5 MB 72.5 kB/s eta 0:00:51
   --------------------------- ------------ 7.9/11.5 MB 72.5 kB/s eta 0:00:51
   --------------------------- ------------ 7.9/11.5 MB 72.5 kB/s eta 0:00:51
   --------------------------- ------------ 7.9/11.5 MB 72.5 kB/s eta 0:00:51
   --------------------------- ------------ 7.9/11.5 MB 72.5 kB/s eta 0:00:51
   --------------------------- ------------ 7.9/11.5 MB 72.5 kB/s eta 0:00:51
   --------------------------- ------------ 7.9/11.5 MB 72.5 kB/s eta 0:00:51
   --------------------------- ------------ 7.9/11.5 MB 72.5 kB/s eta 0:00:51
   --------------------------- ------------ 7.9/11.5 MB 72.5 kB/s eta 0:00:51
   --------------------------- ------------ 7.9/11.5 MB 72.5 kB/s eta 0:00:51
   --------------------------- ------------ 7.9/11.5 MB 72.5 kB/s eta 0:00:51
   --------------------------- ------------ 7.9/11.5 MB 72.5 kB/s eta 0:00:51
   --------------------------- ------------ 7.9/11.5 MB 72.5 kB/s eta 0:00:51

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting pandas
  Using cached pandas-2.2.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Using cached numpy-2.2.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jsr\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Using cached tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\jsr\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-2.2.3-cp312-cp312-win_amd64.whl (11.5 MB)
Downloading numpy-2.2.1-cp312-cp312-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 161.3 kB/s eta 0:01:15
   - -------------------------------------- 0.5/12.6 MB 161.3 kB/s eta 0:01:15
   - -------------------------------------- 0.5/12.6 MB 161.3 kB/s eta 0:01:15
   - -------------------------------------- 0.5/12.6 MB 161.3 kB/s eta 0:01:15
   -- ------------------------------------- 0.8/12.6 MB 211.1 kB/s eta 0:00:57
   -- ------------------------------------- 0.8/12.6 MB 211.1 kB/s eta 0:00:57
   -- ------------------------------------- 0.8/12.6 MB 211.1 kB/s eta 0:00:57
   -- ------------------------------------- 0.8/12.6 MB 211.1 kB/s eta 0:00:57
   -- ------------------------------------- 0.8/12.6 MB 211.1 kB/s eta 0:00:57
   -- ------------------------------------- 0.8/12.6 MB 211.1 kB/s eta 0:00:57
   -- ------------------------------------- 0.8/12.6 MB 211.1 kB/s eta 0:00:57
   -- ------------------------------------- 0.8/12.6 MB 211.1 kB/s eta 0:00:57
   --- ------------------------------------ 1.0/12.6 MB 185.7 kB/s eta 0:01:03
   --- ------------------------------------ 1.0/12.6 MB 185.7 kB/s eta 0:01:03
   --- ------------------------------------ 1.0/12.6 MB 185.7 kB/s eta 0:01:03
   --- ------------------------------------ 1.0/12.6 MB 185.7 kB/s eta 0:01:03
   --- ------------------------------------ 1.0/12.6 MB 185.7 kB/s eta 0:01:03
   --- ------------------------------------ 1.0/12.6 MB 185.7 kB/s eta 0:01:03
   --- ------------------------------------ 1.0/12.6 MB 185.7 kB/s eta 0:01:03
   ---- ----------------------------------- 1.3/12.6 MB 178.5 kB/s eta 0:01:04
   ---- ----------------------------------- 1.3/12.6 MB 178.5 kB/s eta 0:01:04
   ---- ----------------------------------- 1.3/12.6 MB 178.5 kB/s eta 0:01:04
   ---- ----------------------------------- 1.3/12.6 MB 178.5 kB/s eta 0:01:04
   ---- ----------------------------------- 1.3/12.6 MB 178.5 kB/s eta 0:01:04
   ---- ----------------------------------- 1.3/12.6 MB 178.5 kB/s eta 0:01:04
   ---- ----------------------------------- 1.3/12.6 MB 178.5 kB/s eta 0:01:04
   ---- ----------------------------------- 1.3/12.6 MB 178.5 kB/s eta 0:01:04
   ---- ----------------------------------- 1.6/12.6 MB 173.7 kB/s eta 0:01:04
   ---- ----------------------------------- 1.6/12.6 MB 173.7 kB/s eta 0:01:04
   ---- ----------------------------------- 1.6/12.6 MB 173.7 kB/s eta 0:01:04
   ---- ----------------------------------- 1.6/12.6 MB 173.7 kB/s eta 0:01:04
   ---- ----------------------------------- 1.6/12.6 MB 173.7 kB/s eta 0:01:04
   ---- ----------------------------------- 1.6/12.6 MB 173.7 kB/s eta 0:01:04
   ---- ----------------------------------- 1.6/12.6 MB 173.7 kB/s eta 0:01:04
   ---- ----------------------------------- 1.6/12.6 MB 173.7 kB/s eta 0:01:04
   ---- ----------------------------------- 1.6/12.6 MB 173.7 kB/s eta 0:01:04
   ---- ----------------------------------- 1.6/12.6 MB 173.7 kB/s eta 0:01:04
   ---- ----------------------------------- 1.6/12.6 MB 173.7 kB/s eta 0:01:04
   ---- ----------------------------------- 1.6/12.6 MB 173.7 kB/s eta 0:01:04
   ---- ----------------------------------- 1.6/12.6 MB 173.7 kB/s eta 0:01:04
   ---- ----------------------------------- 1.6/12.6 MB 173.7 kB/s eta 0:01:04
   ---- ----------------------------------- 1.6/12.6 MB 173.7 kB/s eta 0:01:04
   ---- ----------------------------------- 1.6/12.6 MB 173.7 kB/s eta 0:01:04
   ---- ----------------------------------- 1.6/12.6 MB 173.7 kB/s eta 0:01:04
   ----- ---------------------------------- 1.8/12.6 MB 138.7 kB/s eta 0:01:18
   ----- ---------------------------------- 1.8/12.6 MB 138.7 kB/s eta 0:01:18
   ----- ---------------------------------- 1.8/12.6 MB 138.7 kB/s eta 0:01:18
   ----- ---------------------------------- 1.8/12.6 MB 138.7 kB/s eta 0:01:18
   ----- ---------------------------------- 1.8/12.6 MB 138.7 kB/s eta 0:01:18
   ----- ---------------------------------- 1.8/12.6 MB 138.7 kB/s eta 0:01:18
   ----- ---------------------------------- 1.8/12.6 MB 138.7 kB/s eta 0:01:18
   ----- ---------------------------------- 1.8/12.6 MB 138.7 kB/s eta 0:01:18
   ----- ---------------------------------- 1.8/12.6 MB 138.7 kB/s eta 0:01:18
   ----- ---------------------------------- 1.8/12.6 MB 138.7 kB/s eta 0:01:18
   ----- ---------------------------------- 1.8/12.6 MB 138.7 kB/s eta 0:01:18
   ----- ---------------------------------- 1.8/12.6 MB 138.7 kB/s eta 0:01:18
   ----- ---------------------------------- 1.8/12.6 MB 138.7 kB/s eta 0:01:18
   ----- ---------------------------------- 1.8/12.6 MB 138.7 kB/s eta 0:01:18
   ----- ---------------------------------- 1.8/12.6 MB 138.7 kB/s eta 0:01:18
   ------ --------------------------------- 2.1/12.6 MB 125.9 kB/s eta 0:01:24
   ------ --------------------------------- 2.1/12.6 MB 125.9 kB/s eta 0:01:24
   ------ --------------------------------- 2.1/12.6 MB 125.9 kB/s eta 0:01:24
   ------ --------------------------------- 2.1/12.6 MB 125.9 kB/s eta 0:01:24
   ------ --------------------------------- 2.1/12.6 MB 125.9 kB/s eta 0:01:24
   ------ --------------------------------- 2.1/12.6 MB 125.9 kB/s eta 0:01:24
   ------ --------------------------------- 2.1/12.6 MB 125.9 kB/s eta 0:01:24
   ------ --------------------------------- 2.1/12.6 MB 125.9 kB/s eta 0:01:24
   ------ --------------------------------- 2.1/12.6 MB 125.9 kB/s eta 0:01:24
   ------ --------------------------------- 2.1/12.6 MB 125.9 kB/s eta 0:01:24
   ------ --------------------------------- 2.1/12.6 MB 125.9 kB/s eta 0:01:24
   ------ --------------------------------- 2.1/12.6 MB 125.9 kB/s eta 0:01:24
   ------ --------------------------------- 2.1/12.6 MB 125.9 kB/s eta 0:01:24
   ------ --------------------------------- 2.1/12.6 MB 125.9 kB/s eta 0:01:24
   ------ --------------------------------- 2.1/12.6 MB 125.9 kB/s eta 0:01:24
   ------ --------------------------------- 2.1/12.6 MB 125.9 kB/s eta 0:01:24
   ------ --------------------------------- 2.1/12.6 MB 125.9 kB/s eta 0:01:24
   ------ --------------------------------- 2.1/12.6 MB 125.9 kB/s eta 0:01:24
   ------ --------------------------------- 2.1/12.6 MB 125.9 kB/s eta 0:01:24
   ------ --------------------------------- 2.1/12.6 MB 125.9 kB/s eta 0:01:24
   ------ --------------------------------- 2.1/12.6 MB 125.9 kB/s eta 0:01:24
   ------ --------------------------------- 2.1/12.6 MB 125.9 kB/s eta 0:01:24
   ------ --------------------------------- 2.1/12.6 MB 125.9 kB/s eta 0:01:24
   ------ --------------------------------- 2.1/12.6 MB 125.9 kB/s eta 0:01:24
   ------- -------------------------------- 2.4/12.6 MB 106.2 kB/s eta 0:01:37
   ------- -------------------------------- 2.4/12.6 MB 106.2 kB/s eta 0:01:37
   ------- -------------------------------- 2.4/12.6 MB 106.2 kB/s eta 0:01:37
   ------- -------------------------------- 2.4/12.6 MB 106.2 kB/s eta 0:01:37
   ------- -------------------------------- 2.4/12.6 MB 106.2 kB/s eta 0:01:37
   ------- -------------------------------- 2.4/12.6 MB 106.2 kB/s eta 0:01:37
   ------- -------------------------------- 2.4/12.6 MB 106.2 kB/s eta 0:01:37
   ------- -------------------------------- 2.4/12.6 MB 106.2 kB/s eta 0:01:37
   ------- -------------------------------- 2.4/12.6 MB 106.2 kB/s eta 0:01:37
   ------- -------------------------------- 2.4/12.6 MB 106.2 kB/s eta 0:01:37
   ------- -------------------------------- 2.4/12.6 MB 106.2 kB/s eta 0:01:37
   ------- -------------------------------- 2.4/12.6 MB 106.2 kB/s eta 0:01:37
   ------- -------------------------------- 2.4/12.6 MB 106.2 kB/s eta 0:01:37
   ------- -------------------------------- 2.4/12.6 MB 106.2 kB/s eta 0:01:37
   ------- -------------------------------- 2.4/12.6 MB 106.2 kB/s eta 0:01:37
   ------- -------------------------------- 2.4/12.6 MB 106.2 kB/s eta 0:01:37
   ------- -------------------------------- 2.4/12.6 MB 106.2 kB/s eta 0:01:37
   ------- -------------------------------- 2.4/12.6 MB 106.2 kB/s eta 0:01:37
   ------- -------------------------------- 2.4/12.6 MB 106.2 kB/s eta 0:01:37
   ------- -------------------------------- 2.4/12.6 MB 106.2 kB/s eta 0:01:37
   ------- -------------------------------- 2.4/12.6 MB 106.2 kB/s eta 0:01:37
   ------- -------------------------------- 2.4/12.6 MB 106.2 kB/s eta 0:01:37
   ------- -------------------------------- 2.4/12.6 MB 106.2 kB/s eta 0:01:37
   ------- -------------------------------- 2.4/12.6 MB 106.2 kB/s eta 0:01:37
   ------- -------------------------------- 2.4/12.6 MB 106.2 kB/s eta 0:01:37
   ------- -------------------------------- 2.4/12.6 MB 106.2 kB/s eta 0:01:37
   ------- -------------------------------- 2.4/12.6 MB 106.2 kB/s eta 0:01:37
   ------- -------------------------------- 2.4/12.6 MB 106.2 kB/s eta 0:01:37
   ------- -------------------------------- 2.4/12.6 MB 106.2 kB/s eta 0:01:37
   -------- ------------------------------- 2.6/12.6 MB 90.9 kB/s eta 0:01:50
   -------- ------------------------------- 2.6/12.6 MB 90.9 kB/s eta 0:01:50
   -------- ------------------------------- 2.6/12.6 MB 90.9 kB/s eta 0:01:50
   -------- ------------------------------- 2.6/12.6 MB 90.9 kB/s eta 0:01:50
   -------- ------------------------------- 2.6/12.6 MB 90.9 kB/s eta 0:01:50
   -------- ------------------------------- 2.6/12.6 MB 90.9 kB/s eta 0:01:50
   -------- ------------------------------- 2.6/12.6 MB 90.9 kB/s eta 0:01:50
   -------- ------------------------------- 2.6/12.6 MB 90.9 kB/s eta 0:01:50
   -------- ------------------------------- 2.6/12.6 MB 90.9 kB/s eta 0:01:50
   -------- ------------------------------- 2.6/12.6 MB 90.9 kB/s eta 0:01:50
   -------- ------------------------------- 2.6/12.6 MB 90.9 kB/s eta 0:01:50
   -------- ------------------------------- 2.6/12.6 MB 90.9 kB/s eta 0:01:50
   -------- ------------------------------- 2.6/12.6 MB 90.9 kB/s eta 0:01:50
   -------- ------------------------------- 2.6/12.6 MB 90.9 kB/s eta 0:01:50
   -------- ------------------------------- 2.6/12.6 MB 90.9 kB/s eta 0:01:50
   -------- ------------------------------- 2.6/12.6 MB 90.9 kB/s eta 0:01:50
   -------- ------------------------------- 2.6/12.6 MB 90.9 kB/s eta 0:01:50
   -------- ------------------------------- 2.6/12.6 MB 90.9 kB/s eta 0:01:50
   -------- ------------------------------- 2.6/12.6 MB 90.9 kB/s eta 0:01:50
   -------- ------------------------------- 2.6/12.6 MB 90.9 kB/s eta 0:01:50
   -------- ------------------------------- 2.6/12.6 MB 90.9 kB/s eta 0:01:50
   -------- ------------------------------- 2.6/12.6 MB 90.9 kB/s eta 0:01:50
   -------- ------------------------------- 2.6/12.6 MB 90.9 kB/s eta 0:01:50
   -------- ------------------------------- 2.6/12.6 MB 90.9 kB/s eta 0:01:50
   -------- ------------------------------- 2.6/12.6 MB 90.9 kB/s eta 0:01:50
   -------- ------------------------------- 2.6/12.6 MB 90.9 kB/s eta 0:01:50
   -------- ------------------------------- 2.6/12.6 MB 90.9 kB/s eta 0:01:50
   --------- ------------------------------ 2.9/12.6 MB 71.7 kB/s eta 0:02:16
   --------- ------------------------------ 2.9/12.6 MB 71.7 kB/s eta 0:02:16
   --------- ------------------------------ 2.9/12.6 MB 71.7 kB/s eta 0:02:16
   --------- ------------------------------ 2.9/12.6 MB 71.7 kB/s eta 0:02:16
   --------- ------------------------------ 2.9/12.6 MB 71.7 kB/s eta 0:02:16
   --------- ------------------------------ 2.9/12.6 MB 71.7 kB/s eta 0:02:16
   --------- ------------------------------ 2.9/12.6 MB 71.7 kB/s eta 0:02:16
   --------- ------------------------------ 2.9/12.6 MB 71.7 kB/s eta 0:02:16
   --------- ------------------------------ 2.9/12.6 MB 71.7 kB/s eta 0:02:16
   --------- ------------------------------ 2.9/12.6 MB 71.7 kB/s eta 0:02:16
   --------- ------------------------------ 2.9/12.6 MB 71.7 kB/s eta 0:02:16
   --------- ------------------------------ 2.9/12.6 MB 71.7 kB/s eta 0:02:16
   --------- ------------------------------ 2.9/12.6 MB 71.7 kB/s eta 0:02:16
   --------- ------------------------------ 2.9/12.6 MB 71.7 kB/s eta 0:02:16
   --------- ------------------------------ 2.9/12.6 MB 71.7 kB/s eta 0:02:16
   --------- ------------------------------ 2.9/12.6 MB 71.7 kB/s eta 0:02:16
   --------- ------------------------------ 2.9/12.6 MB 71.7 kB/s eta 0:02:16
   --------- ------------------------------ 2.9/12.6 MB 71.7 kB/s eta 0:02:16
   --------- ------------------------------ 2.9/12.6 MB 71.7 kB/s eta 0:02:16
   --------- ------------------------------ 2.9/12.6 MB 71.7 kB/s eta 0:02:16
   --------- ------------------------------ 2.9/12.6 MB 71.7 kB/s eta 0:02:16
   --------- ------------------------------ 2.9/12.6 MB 71.7 kB/s eta 0:02:16
   --------- ------------------------------ 3.1/12.6 MB 54.1 kB/s eta 0:02:55
   --------- ------------------------------ 3.1/12.6 MB 54.1 kB/s eta 0:02:55
   --------- ------------------------------ 3.1/12.6 MB 54.1 kB/s eta 0:02:55
   --------- ------------------------------ 3.1/12.6 MB 54.1 kB/s eta 0:02:55
   --------- ------------------------------ 3.1/12.6 MB 54.1 kB/s eta 0:02:55
   --------- ------------------------------ 3.1/12.6 MB 54.1 kB/s eta 0:02:55
   --------- ------------------------------ 3.1/12.6 MB 54.1 kB/s eta 0:02:55
   --------- ------------------------------ 3.1/12.6 MB 54.1 kB/s eta 0:02:55
   --------- ------------------------------ 3.1/12.6 MB 54.1 kB/s eta 0:02:55
   --------- ------------------------------ 3.1/12.6 MB 54.1 kB/s eta 0:02:55
   --------- ------------------------------ 3.1/12.6 MB 54.1 kB/s eta 0:02:55
   --------- ------------------------------ 3.1/12.6 MB 54.1 kB/s eta 0:02:55
   --------- ------------------------------ 3.1/12.6 MB 54.1 kB/s eta 0:02:55
   --------- ------------------------------ 3.1/12.6 MB 54.1 kB/s eta 0:02:55
   --------- ------------------------------ 3.1/12.6 MB 54.1 kB/s eta 0:02:55
   --------- ------------------------------ 3.1/12.6 MB 54.1 kB/s eta 0:02:55
   --------- ------------------------------ 3.1/12.6 MB 54.1 kB/s eta 0:02:55
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ---------- ----------------------------- 3.4/12.6 MB 54.5 kB/s eta 0:02:50
   ----------- ---------------------------- 3.7/12.6 MB 44.1 kB/s eta 0:03:24
   ----------- ---------------------------- 3.7/12.6 MB 44.1 kB/s eta 0:03:24

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
import pandas as pd
pd.DataFrame({'A':[1,2,3]})
data = pd.read_csv("experience_salary_data.csv")

In [7]:
data

     year of experience        salary
0              1.239182  52478.364695
1             13.425406  76850.812956
2             12.811853  75623.705189
3              7.162558  64325.115493
4             10.168967  70337.934130
..                  ...           ...
495           19.341608  88683.216169
496            1.605911  53211.822064
497           15.882086  81764.171707
498           15.550100  81100.200877
499            5.099850  60199.699524

[500 rows x 2 columns]

In [8]:
data.head(10)

   year of experience        salary
0            1.239182  52478.364695
1           13.425406  76850.812956
2           12.811853  75623.705189
3            7.162558  64325.115493
4           10.168967  70337.934130
5           15.704892  81409.784698
6           14.693146  79386.292341
7           18.453829  86907.658537
8            2.546943  55093.885492
9           10.381610  70763.220049

In [10]:
data.round(2)

     year of experience    salary
0                  1.24  52478.36
1                 13.43  76850.81
2                 12.81  75623.71
3                  7.16  64325.12
4                 10.17  70337.93
..                  ...       ...
495               19.34  88683.22
496                1.61  53211.82
497               15.88  81764.17
498               15.55  81100.20
499                5.10  60199.70

[500 rows x 2 columns]

In [11]:
data.tail(10)

     year of experience        salary
490            6.546801  63093.601686
491            1.574510  53149.020903
492           17.866378  85732.755840
493            2.622609  55245.218657
494            3.544682  57089.364292
495           19.341608  88683.216169
496            1.605911  53211.822064
497           15.882086  81764.171707
498           15.550100  81100.200877
499            5.099850  60199.699524

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   year of experience  500 non-null    float64
 1   salary              500 non-null    float64
dtypes: float64(2)
memory usage: 7.9 KB

In [13]:
data.isna().sum()

year of experience    0
salary                0
dtype: int64

In [14]:
data.describe()

       year of experience        salary
count          500.000000    500.000000
mean            10.884437  71768.873618
std              5.541345  11082.689968
min              1.004539  52009.078385
25%              6.335433  62670.866446
50%             11.117777  72235.554029
75%             15.881748  81763.496145
max             19.983918  89967.835930

In [3]:
import pandas as pd
import numpy as np

In [5]:
data = {

"Flight_ID": [f"FL{str(i).zfill(4)}" for i in range(1,101)],

"Airline": np.random.choice(["Airline A", "Airline B", "Airline C", "Airline D"], size=100),

"Departure_Airport": np.random.choice(["JFK","LAX","ORD", "ATL", "DFW"],size=100),

"Arrival_Airport": np.random.choice(["SFO", "SEA", "MIA", "BOS", "DEN"], size=100),

"Departure_Time":pd.date_range("2025-01-01 08:00:00", periods=100, freq="h"),

" Arrival":pd.date_range("2025-01-01 12:00:00", periods=100, freq="h"),

"Delay":np.random.randint(-30,180, size=100)

}
df = pd.DataFrame(data)
df

,Flight_ID,Airline,Departure_Airport,Arrival_Airport,Departure_Time,Arrival,Delay
0,FL0001,Airline B,ORD,MIA,2025-01-01 08:00:00,2025-01-01 12:00:00,69
1,FL0002,Airline B,LAX,DEN,2025-01-01 09:00:00,2025-01-01 13:00:00,68
2,FL0003,Airline C,ORD,DEN,2025-01-01 10:00:00,2025-01-01 14:00:00,79
3,FL0004,Airline A,DFW,MIA,2025-01-01 11:00:00,2025-01-01 15:00:00,-21
4,FL0005,Airline D,ORD,SEA,2025-01-01 12:00:00,2025-01-01 16:00:00,79
...,...,...,...,...,...,...,...
95,FL0096,Airline D,ATL,BOS,2025-01-05 07:00:00,2025-01-05 11:00:00,111
96,FL0097,Airline B,DFW,BOS,2025-01-05 08:00:00,2025-01-05 12:00:00,104
97,FL0098,Airline C,ATL,MIA,2025-01-05 09:00:00,2025-01-05 13:00:00,-17
98,FL0099,Airline C,ATL,MIA,2025-01-05 10:00:00,2025-01-05 14:00:00,91
99,FL0100,Airline C,DFW,SEA,2025-01-05 11:00:00,2025-01-05 15:00:00,0

In [6]:
df["Delay"] =df["Delay"].apply(lambda x: max(0,x))
average_delay_airline = df.groupby("Airline")["Delay"].mean()
print("Average delay by Airline:")

print(average_delay_airline)
average_delay_airline = df.groupby("Departure_Airport")["Delay"].mean()
print("\nAverage Delay by departure Airport:")

Average delay by Airline:
Airline
Airline A    60.400000
Airline B    76.851852
Airline C    61.035714
Airline D    59.080000
Name: Delay, dtype: float64

Average Delay by departure Airport:

In [10]:
print(average_delay_airline)
least_delay_airline = average_delay_airline.idxmin()
most_delay_airline = average_delay_airline.idxmax()
print(f"\nAirline withh least Delay: {least_delay_airline} ({average_delay_airline[least_delay_airline]:.2f} mins)")

print(f"Airline with most Delay : {most_delay_airline} ({average_delay_airline[most_delay_airline]:.2f})")
mean_delay = np.mean(df["Delay"])

Departure_Airport
ATL    58.428571
DFW    52.318182
JFK    65.333333
LAX    73.470588
ORD    83.800000
Name: Delay, dtype: float64

Airline withh least Delay: DFW (52.32 mins)
Airline with most Delay : ORD (83.80)

In [11]:
median_delay = np.median(df["Delay"])
std_dev_delay = np.std(df["Delay"])
percentile_90 = np.percentile(df["Delay"], 90)

In [12]:
print("\nDelay Statistics")
print(f"mean_delay: {mean_delay:.2f}mins")
print(f"median_delay: {median_delay:.2f} mins")
print(f"standard Devition: {std_dev_delay:.2f} mins")
print(f"90th percentile: {percentile_90:.2f} mins")

Delay Statistics
mean_delay: 64.69mins
median_delay: 57.00 mins
standard Devition: 55.56 mins
90th percentile: 149.40 mins

NameError: name 'plt' is not defined